### PR TITLE
2 ➡️ 5

### PR DESCRIPTION
**Pull request by jennuine**
# ➡️ Forward port

Port `ign-launch2` to `ign-launch5`

Branch comparison: https://github.com/gazebosim/gz-launch/compare/ign-launch5...ign-launch2

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by mabelzhang** [comment]
Argh, looks like UNIT_ign_TEST failed on something else in Bionic. Will check tomorrow.

**Comment by mabelzhang** [comment]
I reverted the `Ls` test because I wasn't running it correctly locally, which was why it failed for me. It was supposed to be run from the `build/ignition-launch5` directory, where the `CMakeFiles` and `Makefile` files in the test are to be found. I ran it from the top of the workspace and thought it was broken, but it was actually fine.

But the other tests were failing because they couldn't even find the `ign launch` subcommand. That is weird. I reverted the `IGN_CONFIG_PATH` changes, thinking maybe that has something to do with it... because I don't see anything else that could have caused the subcommand not to be found. Let's see what the CI says.

If that doesn't fix it, maybe we should look at this PR further how it replaced that environment variable... https://github.com/gazebosim/gz-launch/pull/120/commits/f76990e510f0d40d5e58bfcd4797a3369b069d3a
As of now, the tests aren't using that variable anymore.

**Comment by mabelzhang** [comment]
All CI passing except for Windows.
All 7 tests in `UNIT_ign_TEST` are failing on Windows, but actually it looks like they were never passing on Windows in the original port to Windows? That PR had all 6 tests (1 is new since) failing on Windows too https://github.com/gazebosim/gz-launch/pull/120

(With tests passing on Ubuntu after the reverts, I guess that means the `IGN_CONFIG_PATH` has to be set the original way it was. I think it was failing for us locally because there were some artifacts from before that variable was removed in https://github.com/gazebosim/gz-launch/pull/120/commits/f76990e510f0d40d5e58bfcd4797a3369b069d3a, and using it in the custom execution string like `IGN_CONFIG_PATH=/path` was not liked by the tests.)

**Comment by chapulina** [comment]
Yeah the Windows test failures are pre-existing:

https://build.osrfoundation.org/job/ign_launch-ign-5-win/14/#showFailuresLink

This PR looks good to me, it would just be nice to squash the last 3 commits and suffix the commit message with `(#180)` so that it points back to this PR after merged.

**Comment by jennuine** [comment]
> This PR looks good to me, it would just be nice to squash the last 3 commits and suffix the commit message with (#180) so that it points back to this PR after merged.

Done 6ca4edb88eea1ff0a9dc9a517fb571063b563fcf

Thanks for the help @mabelzhang !

**Comment by jennuine** [comment]
> Yeah the Windows test failures are pre-existing:

Should we disable these tests for windows?

**Comment by chapulina** [comment]
> Should we disable these tests for windows?

Yeah the command line ones definitely. The other one may be fixable. That can come in a separate PR though.

**Review by chapulina — APPROVED** [review]

**Pull request merged**
