### PR TITLE
 Fix websocket proto request handling 

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

Depends on https://github.com/gazebosim/gz-msgs/issues/470

Fixes https://github.com/gazebosim/gz-launch/issues/246

## Summary

Added workaround to fix websocket proto message request. Duplicate message types should be removed in https://github.com/gazebosim/gz-msgs/issues/470. In addition, nested messages also leads to duplicate messages so worked around it by leaving it out of the response. 

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by VincidaB — APPROVED** [review]
Tested it on Harmonic and it works for me. 
Only certain shapes are displayed but that's another problem on the gz-web side right  ?

**Review by ahcorde — APPROVED** [review]

**Comment by iche033** [comment]
yes gzweb is missing support for shapes like like cone and ellipsoid, which are added in newer versions of gz

**Comment by VincidaB** [comment]
Made a PR there to add the support  : https://github.com/gazebo-web/gzweb/pull/62
gzweb seem to not have received support in a long time, is the project dead ?

**Comment by iche033** [comment]
Thanks for the PR in gzweb. I think the gzweb team is focusing on something else. The project is still used by different groups of people. The devs are just not working on adding new features at the moment.

**Comment by arilow** [comment]
@mergifyio backport gz-launch7

**Comment by azeey** [comment]
https://github.com/Mergifyio backport gz-launch7

**Pull request merged**
