### PR TITLE
Update copyright to 2022

### PR DESCRIPTION
**Pull request by j-rivero**
Trivial PR for testing all the CI mechanisms after the org/name transition.

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by chapulina** [comment]
I believe this can be closed now

**Pull request closed without merging**
